globalReplacements:
  - key: AcceleratorPrefix
    type: String
    value: AWSAccelerator
  - key: HomeRegion
    type: String
    value: us-east-1  # <-- UPDATE
  - key: EnabledRegions
    type: StringList
    value:
      - "us-east-1"   # <-- UPDATE
